### ISSUE TITLE
build

### ISSUE THREAD

**Issue by deejay87** [Extrasklep/openrevolution#1]
Hi
Trying to build on windows, got this error

src/rt_player/main.cpp:12:10: fatal error: termios.h: No such file or directory
   12 | #include <termios.h>
      |          ^~~~~~~~~~~
compilation terminated.

Thanks

**Comment by Extrasklep** [comment]
I'm not sure if you can get termios to work with the standard windows compiler but you should be able to build this with mingw or something similar, and if you care only about the converter and not the player you can just ignore that error.

**Comment by FreeApp2014** [comment]
Agree, got this to build on windows 10 using MSYS2 and it works just fine

**Comment by deejay87** [comment]
ok how do you build with MSYS2 ? i use the this one too and Mingw64
Thanks

**Comment by Extrasklep** [comment]
I don't know how to fix this, ask someone who knows stuff about msys2 and like I said before if you only care about brstm_converter you can just ignore that error and use the converter

**Comment by deejay87** [comment]
oki thanks
